---
- name: Deploy Speaches AI
  hosts: kvasir
  become: yes

  vars_files:
    - ../../secrets.yml

  roles:
    - role: docker_service
      vars:
        service_name: speaches
        compose_template: speaches-compose.yml.j2
        docker_compose_state: present
