---
- name: Deploy Rclone to Backblaze
  hosts: melinoe
  become: yes

  roles:
    - role: docker_service
      vars:
        service_name: rclone-to-backblaze
        compose_template: rclone-to-backblaze-compose.yml.j2
        docker_compose_state: present
