---
- name: Deploy Uneventful
  hosts: melinoe
  become: yes

  vars:
    uneventful_app_base_url: "https://uneventful.bawdyshop.space"

  vars_files:
    - "../secrets/vault_vars.yml"

  roles:
    - role: docker_service
      vars:
        service_name: uneventful
        compose_template: uneventful-compose.yml.j2
        docker_compose_state: restarted
