---
- name: Deploy Rclone to Backblaze
  hosts: metis
  become: yes

  vars_files:
    - ../../secrets.yml

  roles:
    - role: docker_service
      vars:
        service_name: rclone-to-backblaze
        compose_template: rclone-to-backblaze-compose.yml.j2
        config_files:
          - src: rclone.conf.j2
            dest: rclone.conf
        docker_compose_state: present
