---
- name: Deploy Uneventful
  hosts: metis
  become: yes

  vars:
    uneventful_app_base_url: "https://uneventful.bawdyshop.space"

  vars_files:
    - ../../secrets.yml

  roles:
    - role: docker_service
      vars:
        service_name: uneventful
        compose_template: uneventful-compose.yml.j2
        docker_compose_state: present
