---
- name: Deploy Tautulli
  hosts: melinoe
  become: yes

  roles:
    - role: docker_service
      vars:
        service_name: tautulli
        compose_template: tautulli-compose.yml.j2
        docker_compose_state: restarted
