- name: My first playbook
  hosts: all
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Run Whoami
      ansible.builtin.shell: whoami
      register: whoami

    - name: Display the standard output
      ansible.builtin.debug:
        var: whoami.stdout
