---
- name: Deploy Caddy
  import_playbook: services/deploy_pihole.yaml
  
- name: Deploy Caddy
  import_playbook: services/deploy_caddy.yaml

- name: Deploy Dashboard
  import_playbook: services/deploy_dashboard.yaml
